spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopper
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
  application:
    name: Shopper
    frontend:
      url: http://localhost:5173
  messages:
    encoding: UTF-8
    basename: messages
    cache-duration: 3600

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
      activate-user:
        expiration: 86400000 # a day
      reset-password:
        expiration: 3600000 # 1 hour

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
      springframework:
        web: INFO
  file:
    name: logs/backend.log
